---
title: "Fecal_microbiome_analysis11172016"
author: "Swapna Mahurkar-Joshi"
date: "November 17, 2016"
output: html_document
---

##################

```{r, message = FALSE}
#WGCNA
library(WGCNA)
library(flashClust)
library(vegan)

#Heatmap
library(dplyr)
library(NMF)
library(RColorBrewer)

# multiomiccs
library(vegan)
```

```{r}

setwd("C:/Users/swapnajoshi-admin/Documents/GIT_workspace/IBSmicrobiomeProject/Resequencing/batch1_batch2_merged/New_qiime_analyses_11062016/") 

```

# Import Distance metric for heirarchical clustering of distances measured by unweighted unifrac

```{r}
unwei.dm <- read.delim("C:/Users/swapnajoshi-admin/Documents/GIT_workspace/IBSmicrobiomeProject/Resequencing/batch1_batch2_merged/New_qiime_analyses_11062016/fecal/bdiv_SCOR_feces_rarefied99689/unweighted_unifrac_dm.txt", row.names=1)
# import mapping file
map1 <- read.delim("C:/Users/swapnajoshi-admin/Documents/GIT_workspace/IBSmicrobiomeProject/Resequencing/batch1_batch2_merged/New_qiime_analyses_11062016/fecal/SCORFecesMapFINAL.txt",  sep='\t', row.names=1)

map2<-map1[row.names(map1)%in%colnames(unwei.dm),] ## 2 samples did not have data
map2<-map2[colnames(unwei.dm),]
match(row.names(map2),colnames(unwei.dm))
unwei.dm1<-as.dist(unwei.dm)
sampleTree = flashClust(unwei.dm1)
labels1=map2$Dx
dat.ordered<-unwei.dm[sampleTree$order,]

```

# plot
```{r}
sizeGrWindow(15,12)
par(cex = 0.6);
par(mar = c(0,4,2,0))
plot(sampleTree, main = "Heirarchical Clustering", sub="", xlab="", cex.lab = 1.5, cex.axis = 1.5, cex.main = 2, labels=labels1)
abline(h = 0.65, col = "red")
```

# cluster membership

```{r}
# library(WGCNA)
clust1 = cutreeStatic(sampleTree, cutHeight = 0.65, minSize = 1)
table(clust1)
lab<-map2[sampleTree$labels,]$Group
lab1<-substr(row.names(map2[sampleTree$labels,]),7,11)
df2<-as.data.frame(cbind(clust1,as.character(lab)))
head(df2)
set.seed(123)
rainbow(n=6)
# [1] "#FF0000FF" "#FFFF00FF" "#00FF00FF" "#00FFFFFF" "#0000FFFF" "#FF00FFFF"

df2$color1<-NA
for ( i in 1: 75)
{if (df2[i,1]=="1")
{df2[i,3]<-"green"}
  else if (df2[i,1]=="2")
  {df2[i,3]<-"pink"}
  else if (df2[i,1]=="3")
  {df2[i,3]<-"dark blue"}
}

df2$colorDx<-NA
for ( i in 1: 75)
{if (df2[i,2]=="1")
{df2[i,4]<-"cyan"}
  else if (df2[i,2]=="2")
  {df2[i,4]<-"red"}
}

df2<-cbind(df2, as.character(lab1))

library(dendextend)
png("C:/Users/swapnajoshi-admin/Documents/GIT_workspace/IBSmicrobiomeProject/Resequencing/batch1_batch2_merged/New_qiime_analyses_11062016/fecal/unweightedUnifracDistCompleteHierarchical.png", res = 200, height = 2000, width = 2500)
plot(sampleTree, main = "Heirachical Clustering", sub="", xlab="", cex.lab = 1.5, cex.axis = 1.5, cex.main = 2, labels=lab)
abline(h = 0.65, col = "red")
colored_bars(colors= df2[,c(3,4)], dend = sampleTree, y_shift = 0.3, rowLabels = c("Cluster", "Dx"),sort_by_labels_order 	
= TRUE)
dev.off()

# Cluster membership with IBS as well as healthy controls

mapIbsHcCluster<-map2
mapIbsHcCluster$IbsHcClusterMemb<-clust1

write.table(mapIbsHcCluster, file="C:/Users/swapnajoshi-admin/Documents/GIT_workspace/IBSmicrobiomeProject/Resequencing/batch1_batch2_merged/New_qiime_analyses_11062016/fecal/mapIbsHcClusterBig_unweighClu_fecal.csv",sep=",", col.names=NA)
colnames(mapIbsHcCluster)
# littleIbsMappingIBsHcClust<-mapIbsHcCluster[,c(8,9,10,11,15,16,17,18,20,30:51,76:79)]
# write.table(littleIbsMappingIBsHcClust, file="C:/Users/swapnajoshi-admin/Documents/GIT_workspace/IBSmicrobiomeProject/Resequencing/batch1_batch2_merged/New_qiime_analyses_11062016/fecal/littleIbsMappingIBsHcClust.csv",sep=",", col.names=NA)

save(df2, file="df2.rda")
```


# correlation with clinical traits
```{r}

map4.ibs<- mapIbsHcCluster[mapIbsHcCluster$Group=="2",c(8:9,28, 30,32:39,44:51,78, 99, 129)]
map4_numTraits<-apply(map4.ibs,2,as.numeric)
row.names(map4_numTraits) <- row.names(map4.ibs)

save(map4_numTraits, file="map4_numTraits_weiClu.rda")

p.traits1<-matrix(NA, nrow=23, ncol=1)
for ( i in 1: 22)
{p.traits1[i,1]<-summary(lm(map4_numTraits[,i] ~ map4_numTraits[,23]))$coefficients[,4][2]}
row.names(p.traits1)<-colnames(map4_numTraits)
p.traits1
write.table(p.traits1, file="TraitsIbsClusters_lm.csv", col.names=NA, sep=",")
p.traits1
                            [,1]
BH                   0.019893624
Sex                  0.795725247
HAD_Anxiety          0.078612844
HAD_Depression       0.001540158
ETI_General_Score    0.031327686
ETI_Physical_Score   0.182457506
ETI_Emotional_Score  0.006651484
ETI_Sexual_Score     0.376972009
ETI_Total_Score      0.013141627
CSQ_Score            0.015615366
VSI_Score            0.005952024
PSS_Score            0.003159865
BSQ_OverallSx        0.145389693
BSQ_AbdPain          0.086122214
BSQ_Bloating         0.406955932
BSQ_UsualSeverity    0.066019047
BSQdrv_SxDurationYrs 0.838730922
PHQ_Score            0.148600091
PHQ_Score_noIBSQs    0.206050583
PHQ_Score_noGIQs     0.268391558
ACE_Score            0.051119076
IBSSS_Severity       0.024535729
IbsHcClusterMemb              NA
boxplot(map4_numTraits[,9] ~ as.factor(map4_numTraits[,22]))

map.ibs$colormap.ibs$IbsHcCluster_unweighted 

p <- ggplot(map.ibs, aes(factor(IbsHcCluster_unweighted), ETI_Total_Score, fill= factor(IbsHcCluster_unweighted))) + geom_boxplot() 
p + scale_fill_manual(values = c("green","blue","orange"))

p <- ggplot(map.ibs, aes(factor(IbsHcCluster_unweighted), ETI_Emotional_Score, fill= factor(IbsHcCluster_unweighted))) + geom_boxplot() 
p + scale_fill_manual(values = c("green","blue","orange"))

# PC3 based classification:
  
map1<- read.delim("C:/Users/swapnajoshi-admin/Documents/GIT_workspace/IBSmicrobiomeProject/Resequencing/batch1_batch2_merged/New_qiime_analyses_11062016/mapping_new_cluster_validated.txt", row.names=1)
map1$BH.1 <- gsub(5,6,map1$BH.1)
map.ibs<- map1[map1$Dx=="IBS",c(14:17,19:39)]
map_numTraits<-apply(map.ibs,2,as.numeric)
row.names(map_numTraits) <- row.names(map.ibs)

# save(map4_numTraits, file="map4_numTraits_weiClu.rda")

p.traits1<-matrix(NA, nrow=25, ncol=1)
for ( i in 1: 22)
{p.traits1[i,1]<-summary(lm(map_numTraits[,i] ~ map_numTraits[,25]))$coefficients[,4][2]}
row.names(p.traits1)<-colnames(map_numTraits)
p.traits1
write.table(p.traits1, file="TraitsIbsClustersPC3based_lm.csv", col.names=NA, sep=",")
p.traits1

```

